version: "3.8"

services:
    discoveryserver:
        build:
            context: .
            dockerfile: discoveryserver/Dockerfile
        ports:
            - "8761:8761"
        networks:
            - microservice-networks
    axonserver:
        image: "axoniq/axonserver:latest"
        hostname: axonserver
        container_name: axonserver
        environment:
            - "AXONIQ_AXONSERVER_STANDALONE=TRUE"
        ports:
            - "8024:8024"
            - "8124:8124"
            - "8224:8224"
        networks:
            - microservice-networks
    bookservice:
        build:
            context: .
            dockerfile: bookservice/Dockerfile
        ports:
            - "9001:9001"
        networks:
            - microservice-networks
        depends_on:
            - discoveryserver
            - axonserver
        environment:
            - "AXONIQ_AXONSERVER_SERVERS=axonserver:8024"
    redis:
        image: redis:latest
        restart: always
        hostname: redis
        ports:
            - "6379:6379"
        networks:
            - microservice-networks
    apigateway:
        build:
            context: .
            dockerfile: apigateway/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - microservice-networks
        depends_on:
            - discoveryserver
            - redis
networks:
    microservice-networks:
        driver: bridge
