server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/booklibrary?useSSL=false&serverTimezone=UTC
    username: root
    password: Phuthanh071099

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

