
#-----------------Commonly----------------
# spring:
#   kafka:
#     bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#     consumer:
#       group-id: ${KAFKA_GROUP_ID:default-group}
#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: testspringjms@gmail.com
#     password: hbsv zyer vtjv guga
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#         transport:
#           protocol: smtp

#-----------------Deploy with Docker Compose----------------
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:broker:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:default-group}
  mail:
    host: smtp.gmail.com
    port: 587
    username: testspringjms@gmail.com
    password: hbsv zyer vtjv guga
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp